### ISSUE TITLE
Invalid field chain when Edit Filter

### ISSUE THREAD

**Issue by zalei-odoo** [OCA/spreadsheet#13]
Greetings, using odoo16 I can’t use the filter for the _spreadsheet.dashboard_ model in any way - please clarify - is this a bug or a limitation that requires the purchase of Enterprice version of odoo 16?
**odoo16 version**:
commit d84d41d7559b94f5195fb9b888149b8f30616172 (grafted, HEAD -> 16.0, origin/HEAD, origin/16.0)
Author: Rmi Rahir (rar) <rar@odoo.com>
Date:   Fri Jun 2 10:15:39 2023 +0000
**spreadsheet version**:
commit db8bcbec1deed97639807f7a85a6c763ace56da6 (HEAD -> 16.0, origin/HEAD, origin/16.0)
Author: Sandrine (ACSONE) <sandrine.ravet@acsone.eu>
Date:   Thu May 25 09:49:15 2023 +0000

![изображение](https://github.com/OCA/spreadsheet/assets/123005630/cbe7d5dd-5230-44f9-8ef6-f7745e5f5951)
![изображение](https://github.com/OCA/spreadsheet/assets/123005630/d99c7163-8675-49c1-9fec-40ca132a06b7)

When selecting a field from the pop-up list and saving the parameters, it is possible to select filter values, but they are not applied to the spreadsheet table.
![изображение](https://github.com/OCA/spreadsheet/assets/123005630/95f3540b-e792-41bf-89bf-3c517d647414)

If this is not a limitation or a bug, please explain how to get around this error?

P.S. I apologize for the drawings, but I think I can explain it more clearly.

**Comment by etobella** [comment]
It works properly on runboat and locally, I am unable to see how you created the bug.

**Comment by zalei-odoo** [comment]
I don't started runbot (I have never used it and I doubt that runbot caters for this situation), Locally:
1) Create new database with Demo data.
2) Activate Purchase module.
![изображение](https://github.com/OCA/spreadsheet/assets/123005630/f191440d-67e8-4375-baf6-1eadfdbd6f95)
3) Activate Spreadsheet Oca module.
![изображение](https://github.com/OCA/spreadsheet/assets/123005630/c96bac7e-a443-4a0e-8d82-60e4c8c53c76)
4) Create spreadsheet from menu "Spreadsheets" by clicking "New" button (type "test1" in field name and click "Save manually").
Now I have empty spreadsheet with name "test1".
5) In purchase.order pivot view click button "Add to spreadsheet" and select created spreadsheet with name "test1".
![изображение](https://github.com/OCA/spreadsheet/assets/123005630/878c101a-133b-4b7a-8e24-675d9501f9fb)
Then I can't apply filter by selecting "File - Filters" and clicking some button "Add date", "Add relation" or "Add text" - this situation I describe in my first comment. I see an error triangle with an exclamation point "Invalid field chain".

Probably I do something wrong, help me please, if so...

**Comment by zalei-odoo** [comment]
[etobella](https://github.com/etobella) - Thank you for Pull request https://github.com/OCA/spreadsheet/pull/14. I already tried to test it's changes - the "Invalid field chain" error really disappeared, but when changing the filter values (date, relation or text), the data in the spreadsheet still does not filtered.

**Comment by zalei-odoo** [comment]
[etobella](https://github.com/etobella) - Thank you for Pull request [#14](https://github.com/OCA/spreadsheet/pull/14). I already tried to test it's changes - the "Invalid field chain" error really disappeared, but when changing the filter values (date, relation or text), the data in the spreadsheet still does not filtered.

One more moment - when, after saving the filter, again click on the gear to edit the properties - the selected earlier field in the filter is empty again.

**Comment by zalei-odoo** [comment]
@[etobella](https://github.com/etobella) Thank you!

**Comment by zalei-odoo** [comment]
@[etobella](https://github.com/etobella) Thank you!

**Comment by vuongdz247** [comment]
> [etobella](https://github.com/etobella) - Thank you for Pull request [#14](https://github.com/OCA/spreadsheet/pull/14). I already tried to test it's changes - the "Invalid field chain" error really disappeared, but when changing the filter values (date, relation or text), the data in the spreadsheet still does not filtered.
> 
> One more moment - when, after saving the filter, again click on the gear to edit the properties - the selected earlier field in the filter is empty again.

It's not working for me. Please help me ....

**Comment by vuongdz247** [comment]
> > [etobella](https://github.com/etobella) - Thank you for Pull request [#14](https://github.com/OCA/spreadsheet/pull/14). I already tried to test it's changes - the "Invalid field chain" error really disappeared, but when changing the filter values (date, relation or text), the data in the spreadsheet still does not filtered.
> > One more moment - when, after saving the filter, again click on the gear to edit the properties - the selected earlier field in the filter is empty again.
> 
> It's not working for me. Please help me ....

@zalei-odoo , 
@etobella

**Comment by etobella** [comment]
It does not work in which way ? @vuongdz247

**Comment by vuongdz247** [comment]
" I already tried to test it's changes - the "Invalid field chain" error really disappeared, but when changing the filter values (date, relation or text), the data in the spreadsheet still does not filtered.

One more moment - when, after saving the filter, again click on the gear to edit the properties - the selected earlier field in the filter is empty again."
@etobella please

**Comment by etobella** [comment]
Try again with the new changes...

**Comment by vuongdz247** [comment]
I tried edit #14, but it still doesn't work

**Comment by vuongdz247** [comment]
It worked on the latest edited version. Thank for your help. Have a nice day ...
