### ISSUE TITLE
Xlsx download option

### ISSUE THREAD

**Issue by unique4** [OCA/spreadsheet#16]
Currently, user is only able to download json file. It would be nice to add xlsx download option to spreadsheet.

Similar feature in odoo EE:
![image](https://github.com/OCA/spreadsheet/assets/37263237/8958dde4-f576-4c58-b9e7-ad91afea0f8e)

**Comment by lorenzomorandini** [comment]
This seems quite an important feature, I was surprised to don't find it already.

EDIT: I see this was implemented, thanks! https://github.com/OCA/spreadsheet/commit/34c35a821b70c04dea1ebde8df30856dc5611d11
