### ISSUE TITLE
Automatic data update

### ISSUE THREAD

**Issue by lauraruggerilinea** [OCA/spreadsheet#18]
## Module
spreadsheet_oca

## Describe the bug
When I create a pivot by grouping, for example, by month, it does not automatically insert any rows when new month values ​​are added.
Example I have grouped sales by months and they are in July. When I get to August I can't find the new row opening the spredsheet but I have to delete and recreate it.

**Comment by pedrobaeza** [comment]
This is the same as #8 

@etobella you told that is handled. How?

**Comment by etobella** [comment]
In order to add a new line, you need to reinsert the table (it is added as an option), it cannot be done automatically. Sorry
The same happens with Odoo EE Spreadsheet

**Comment by legalsylvain** [comment]
if it's a recurring question, we could ask a section that mentions that limitation in the ROADMAP.rst section ?

**Comment by etobella** [comment]
Yes, we probably need to do this :disappointed:

**Comment by lauraruggerilinea** [comment]
> In order to add a new line, you need to reinsert the table (it is added as an option), it cannot be done automatically. Sorry The same happens with Odoo EE Spreadsheet

But in Odoo EE there is the Re-Insert pivot key

**Comment by etobella** [comment]
The same here. Click on data. You will see the pivots. Click on the one you want to reinsert. On the right, a menu will appear with the table info and the option to reinsert is there

**Comment by lauraruggerilinea** [comment]
> The same here. Click on data. You will see the pivots. Click on the one you want to reinsert. On the right, a menu will appear with the table info and the option to reinsert is there

Under data menu I have only "Add filter" and "Sort range"

**Comment by etobella** [comment]
Are you using the last version? Did you try on runboat?

**Comment by lauraruggerilinea** [comment]
ok :) i updated the repo and now it works
