### ISSUE TITLE
RFC - Documentation

### ISSUE THREAD

**Issue by legalsylvain** [OCA/spreadsheet#25]
Hi all, (and specially @etobella).
first thanks for this interesting modules.
I'll soon migrate to V16 and I'd like to use OCA / spreadsheet modules that looks promizing. 
But the documentation is very limited. I'd like to propose a PR to add description & screenshot in the readme.

Is the modules working like the odoo EE one ? (https://www.odoo.com/documentation/16.0/applications/finance/spreadsheet.html?highlight=spreadsheet)

thanks.

**Comment by etobella** [comment]
@legalsylvain It works really similary to Odoo EE modules. Certainly, it would be awesome to have some documentation. I had to do it, but it was a project I was doing in my free time and I had several other issues :sob: 
It would be awesome if you can do it!

**Comment by legalsylvain** [comment]
Hi @etobella. I finally found a few time to start to improve the documentation. Feel free to review : https://github.com/OCA/spreadsheet/pull/28
And again, thanks for this awsome work ! 

Note : i have a question, regarding a feature I didn't documented, because I don't understand how it works : the "Add to spreadsheet" feature.

Step to reproduce : 

- Go to contact, create random filter

![image](https://github.com/OCA/spreadsheet/assets/3407482/d3ce83a0-26f9-42e8-b23d-81017b6f47ae)

- Click on "Add to spreadsheet" then "create a spreadsheet"

-  :ok:  the result is great : 

![image](https://github.com/OCA/spreadsheet/assets/3407482/921b39ed-a957-48e6-851a-f6feb46abe39)

-  :ok: If I change the phone of "deco addict in the odoo database, the spreadsheet is updated. (when I refresh the page, or click on "Data > Refresh all data".

- But if I add a new partner, named "Deco Test Sylvain" in the odoo res.partner database, it doesn't appears in my spreadsheet and I didn't find a way to "extend the number of raws". (Except writing manually a new line with for each row, ``=ODOO.LIST(1,N+1,"field_name_of_the_current_row")``
That being said, I don't understand the point of this feature, as adding a new element is a very common situation. Am I missing something? 

Thanks !

**Comment by flotho** [comment]
Is ther any way to import an ods, xlsx or existing spreadsheet?
Addistionnaly, is there any possibility to copy paste datas form an ods/xls file to an Odoo spreadsheet ?
Regards

**Comment by legalsylvain** [comment]
> Is ther any way to import an ods, xlsx or existing spreadsheet?

this is done in o-spreadsheet, in recent version. (xlsx handled) : https://odoo.github.io/o-spreadsheet/

![image](https://github.com/OCA/spreadsheet/assets/3407482/8e10121d-0af9-45c6-a76e-18c5234be853)

>  Addistionnaly, is there any possibility to copy paste datas form an ods/xls file to an Odoo spreadsheet ?

just tested in the odoo demo instance (same link) and it works.

**Comment by legalsylvain** [comment]
Closing this issue, because answered here : https://github.com/OCA/spreadsheet/pull/28

The last comment regarding undocumented feature has no answer.  (https://github.com/OCA/spreadsheet/issues/25#issuecomment-1986132055). I guess it is related to https://github.com/OCA/spreadsheet/issues/8
