### ISSUE TITLE
Error on selecting "Add relation" Filter bug (Invalid props for component 'ModelSelector': 'value' is not a string)

### ISSUE THREAD

**Issue by xavigutipujol** [OCA/spreadsheet#27]
Module

Spreadsheet
Describe the bug

###Error on selecting "Add relation" Filter.
UncaughtPromiseError > OwlError
Promesa desconocida > Invalid props for component 'ModelSelector': 'value' is not a string
To Reproduce

16

    open spreadsheet for any Pivot view
    click on File > Filters
    "Add relation" error will come

![error ModelSelector](https://github.com/OCA/spreadsheet/assets/80115591/b903b4a4-dc14-4143-aa25-70d23ed4b468)

@etobella

**Comment by mlaitinen** [comment]
Related issue: #24
