### ISSUE TITLE
Add new data from models, but the list information in dashboard not updating new data

### ISSUE THREAD

**Issue by Redolvo** [OCA/spreadsheet#30]
## Module
spreadsheet

## Describe the bug
I add my other dummy models data to the spreadsheet
![image](https://github.com/OCA/spreadsheet/assets/117249499/8cb8dc47-3184-47a1-a29a-4c53e5ea0810)

its good, it appears
![image](https://github.com/OCA/spreadsheet/assets/117249499/f6cc9243-d712-4689-880b-bf26508c45d1)

when i edit the data, the data in the spreadsheet change

but when i add new data in the models, the spreadsheet doesnt update the new model

## To Reproduce
1. press add to spreadsheet
2. add new data in the models,
3. the data in the spreadsheet wont change

**Expected behavior**
the data in the spreadsheet should have change according to the models data.

**Comment by legalsylvain** [comment]
Hi @Redolvo. Thanks for your comment. 
I confirm that it is how the software works for the time being. 
AFAIK, that's the same for Odoo Enterprise. Don't you think ? 

Indeed it's a current annoying limitation, but to solve this, it's not very simple.

**Comment by Redolvo** [comment]
Hi @legalsylvain. Thanks for the response.
i dont know that the odoo enterprise also work this way, now that i know it, i will close this issue, thanks for the response.
