### ISSUE TITLE
[IMP] spreadsheet_oca: Add ability to delete pivots and lists via button

### ISSUE THREAD

**Issue by chrisandrewmann** [OCA/spreadsheet#35]
Currently there is no way to delete pivots or lists in the GUI after creation (once added to a spreadsheet)

I added a button and relevant methods to delete, but couldn't find a way to programmatically close the sidepanel without causing it to crash due to OWL lifecycle error.
Only solution I found was to force the "filter" sidebar to load in place after deletion of pivot /list using: this.env.openSidePanel("FilterPanel", {});
Otherwise it works, but maybe someone with more OWL knowledge can improve.

Comments welcome.

PR: https://github.com/OCA/spreadsheet/pull/34

**Comment by pedrobaeza** [comment]
Thanks for the new feature, but no need to create a issue for this having the PR. It's duplicated info. I'm closing it.

**Comment by chrisandrewmann** [comment]
@pedrobaeza Ah ok, sorry. Thought it was required.
