### ISSUE TITLE
Decoding conflict between UTF-8 and LATIN-1

### ISSUE THREAD

**Issue by thecowmilk** [OCA/spreadsheet#42]
## Module
Spreadsheet OCA

## Describe the bug
When uploading an excel file the module would complain about not decoding the starting byte. After some inspections the code was trying to decode a `latin-1` character to `utf-8`.

## To Reproduce
**Affected versions**: 16.0.1.2.4

1. The excel file should be uploaded without the encoding problem.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
This is the same about not being able to upload Excel files.
